// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwRgT5LjlqV0Ztsv3XDyEp1lyuKoRRyPc',
    appId: '1:232510517754:web:d3e78c9abc836d85eaf443',
    messagingSenderId: '232510517754',
    projectId: 'smit-final-exam-project',
    authDomain: 'smit-final-exam-project.firebaseapp.com',
    storageBucket: 'smit-final-exam-project.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZx9cHKWQhruoH5NXBRYUOqsg1CbmlHAo',
    appId: '1:232510517754:android:90e8f384eab7c184eaf443',
    messagingSenderId: '232510517754',
    projectId: 'smit-final-exam-project',
    storageBucket: 'smit-final-exam-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhL97GrRI7hiJk_F0nDWGpiFrU8zOXVrI',
    appId: '1:232510517754:ios:01ac3e7ee5501c51eaf443',
    messagingSenderId: '232510517754',
    projectId: 'smit-final-exam-project',
    storageBucket: 'smit-final-exam-project.firebasestorage.app',
    iosBundleId: 'com.example.smitFinalExamProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhL97GrRI7hiJk_F0nDWGpiFrU8zOXVrI',
    appId: '1:232510517754:ios:01ac3e7ee5501c51eaf443',
    messagingSenderId: '232510517754',
    projectId: 'smit-final-exam-project',
    storageBucket: 'smit-final-exam-project.firebasestorage.app',
    iosBundleId: 'com.example.smitFinalExamProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwRgT5LjlqV0Ztsv3XDyEp1lyuKoRRyPc',
    appId: '1:232510517754:web:336076780d130ec0eaf443',
    messagingSenderId: '232510517754',
    projectId: 'smit-final-exam-project',
    authDomain: 'smit-final-exam-project.firebaseapp.com',
    storageBucket: 'smit-final-exam-project.firebasestorage.app',
  );
}
